### ISSUE TITLE
!help does not show builtin commands

### ISSUE THREAD

**Issue by mcarton** [pipoteam/pipobot#22]
Eg. `!user` does not appear in the global `!help` list. It has its own `!help user` however.

**Comment by sleduc** [comment]
Should be OK with ed63f1a7f38770f98f8e9704af48a8c41179bac4 : the "Help" module needed to be loaded after all other modules.

Otherwise, when constructing the list of modules for the "!help" command, it will not know those that are inserted after it in the "modules" list.

The only command that seemed to be impacteed was indeed the "!user" command, because the "KnownUsersManager" was loaded after it.
